const convertChat = [
  "0",
  "Ai biểu ngu",
  "Cậu không sao chứ?",
  "Không đùa đâu",
  "imghttps://i.imgur.com/JWIUFS2.jpg",
  "t bị ngất và bị trói",
  "tuih noss dangd chở t đi",
  "t vưa tỉnh lai mowrr đươc dây r",
  "Giờ đang ở đâu vậy",
  "Để tớ nhờ người giúp",
  "t đang ở trong thùng xe tải",
  "xe đang chạy",
  "Xe đang chạy á???",
  "t phải làm gì đây?",
  "Nhanh lên tụi nó đang chở t đi đâu đó",
  "Ừ cứu t với",
  "gọi cảnh sastt hay gì đii",
  "ai cũng đucợ",
  "Chờ tí, để t gọi cảnh sát",
  "dcm, không có sóng",
  "bình tĩnh đã, họ sẽ sớm đến thôi",
  "nhanh lên. đt t còn 20% thôi",
  "Làm ơn, tớ sợ lắm. ",
  "Cứu với, xin cậu. Hãy làm gì đóf",
  "Tớ sợ lắm",
  "Nghe này, hãy bình tĩnh",
  "Cậu thử hét lên xem",
  "đừng bỏ rơi tớ",
  "hứa với t đi",
  "tớ sẽ thử",
  "tớ hứa với cậu",
  "Hét lớn lên, biết đâu có ai đó nghe được",
  "khoan đã, đừng làm vậy",
  "Giờ tớ nên làm gì?",
  "Hay cậu thử gọi cho cảnh sát xem. Họ có thể lần ra vị trí",
  "Hét to lên biết đâu có người khác nghe",
  "Họ dừng xe lại",
  "Không kjhong",
  "djvznnnnnnnzc",
  "Lisa. Có chuyenj gì vậy?",
  "imghttps://images.pond5.com/white-glove-hand-holding-bloody-footage-054934724_iconl.jpeg",
  "Tao gieets no roi",
  // 3
  // 4
  // 5
  // 6
  // 7
  //8
  // Từ đây vị trí trong mảng = line - 10
  // CHAT CÓ SẴN
  "fix bug chưa m?",
  "đang đi chơi với crush fix gì ba",
  "imghttps://i.imgur.com/Lwjx2GM.jpg",
  "ngon z ta",
  "hehe",
  "rãnh k chú",
  "giúp với",
  "imghttps://user-images.githubusercontent.com/1610503/30879342-0052f432-a2b4-11e7-8848-eb19f8f1db0b.png",
  "khongggggg",
  "jen oiwiii, mai sinh nhật bạn ấy r",
  "cho t lời khueyen mua quà với",
  "t được gì nếu giúp m??",
  "Sự tôn trọng",
  "Mua cu giả 2 đầu dẻo màu xanh chuối",
  "ok cảm ơn nhe",
  "queo cơm",
  "alo alo",
  "gì đó ku",
  "nãy thấy hình này hài quá gửi m xem",
  "imghttps://www.meme-arsenal.com/memes/8da21b55bbdc8815b9325894b45eab6d.jpg",
  "nhìn mặt nó hài gê",
  "haha",
  "2222",
  "gì nhóc",
  "ăn cơm chưa",
  "rồi, ông ăn chưa",
  "rồi luôn, hehe",
  "hello!",
  "?",
  "t có cái này muốn nói...",
  "đừng",
  "ok bờ rồ",
  "Tin nhắn đã xóa",
  "Lô cc",
  "hello",
  "[Tin nhắn tự động] Tôi đang ngủ, xin đừng làm phiền lúc này!",
  "Ê, dậy chưa",
  "Ê heo.",
  "Gấp, Backend bị DDOS sập rồi",
  "Bạn ơi, lỗ nhị lủng rồi",
  "imghttps://taoanhonline.com/wp-content/uploads/2020/02/anh-tam-trang-14.jpg?v=1582376124",
  "cuuws",
  "sos",
  "t bị ai bắt cóc r",
  "giupz tao với toao sợ quá",
  "Giờ thiên tới ròi homie ơiii",
  // END CHAT CÓ SẴN
  "1111",
  "1111",
  "2222",
  "44444",
];

export default convertChat;
