const convertChat = [
  "xin chào",
  "ê mày rãnh không?",
  "có chuyện gì vậy?",
  "được",
  "chờ một lát",
  "không",
  "ok",
  "đang làm gì đó",
  "ổn không?",
  "chán vl",
  "ừa",
  "đang ăn",
  "không rãnh",
  "đang ăn cơm",
  "fix bug chưa?",
  "mày mua ở đâu vậy",
  "đẹp ghê",
  "Thấy tóc hôm bửa làm đẹp k, hehe",
  "ngu à",
  "cố lên",
  "mình luôn ở đây",
  "cứu",
  "t sợ lắm",
  "không biết sao nữa",
  "giờ làm gì dây",
  "gọi cho ai đó đi",
  "gọi cảnh sát",
  "nó ở đây",
  "ngoài kia",
  "t đói quá",
  "và sợ nữa",
  "làm ơn",
  "mình không muonson chết dâudu",
  "cuuuwus minhfh vơiss",
  "từ lúc nào?",
  "giờ đang ở đâu",
  "t không biết",
  "lúc nào m cũng xinh đẹp hết :)",
  "xạo vừa thôi",
  "thiệtttttt",
  "m mà làm idol là t đu liền",
  "mai qua chở t đi nha",
  "ok, mai gặp, có bất ngờ cho m lun",
  "m chơi với nó lâu, m biết nó thích gì k?",
  "ê, mốt sinh nhật crush ròiiii",
  "tao có được gì k?",
  "có, mày được xem con bạn thân m hạnh phúc :))",
  "nói chứ chỉ t đi, t giới hiệu cho m cho thằng Long",
  "a Long bửa m chở hả",
  "đc đc. để mai t bày cho",
  "ê ê ",
  "có nhỏ này muốn làm quen m nè",
  "ngon, ai z",
  "Jenny, nhỏ bửa gặp rồi á",
  "vl",
  "sao, chịu k",
  "để t cho ẻm fb m",
  "thôi cũng đc, chứ vã quá",
  ":)))",
  "tin nhắn đã bị xóa",
  "bửa nào nhậu anh ơi",
  "để coi chứ dạo này bận quá",
  "a mới chuyển công tác",
  "nào sắp xếp đc có gì a hú m",
  "có đó không",
  "t bị bắt cóc",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
];

export default convertChat;
