const convertChat = [
  "0",
  "Ai biểu ngu",
  "Trời, cậu không sao chứ?",
  "Không đùa đâu",
  "imghttps://i.imgur.com/JWIUFS2.jpg",
  "t bị ngất và bị trói",
  "tuih noss dangd chở t đi",
  "t vưa tỉnh lai mowrr đươc dây r",
  "Giờ đang ở đâu vậy",
  "Để tớ nhờ người giúp",
  "t đang ở trong thùng xe tải",
  "xe đang chạy",
  "Xe đang chạy á???",
  "t phải làm gì đây?",
  "Nhanh lên tụi nó đang chở t đi đâu đó",
  "Ừ cứu t với",
  "gọi cảnh sastt hay gì đii",
  "ai cũng đucợ",
  "Chờ tí, để t gọi cảnh sát",
  "dcm, không có sóng",
  "bình tĩnh đã, họ sẽ sớm đến thôi",
  "nhanh lên. đt t còn 20% thôi",
  "Làm ơn, tớ sợ lắm. ",
  "Cứu với, xin cậu. Hãy làm gì đóf",
  "Tớ sợ lắm",
  "Nghe này, hãy bình tĩnh",
  "Cậu thử hét lên xem",
  "đừng bỏ rơi tớ",
  "hứa với t đi",
  "tớ sẽ thử",
  "tớ hứa với cậu",
  "Hét lớn lên, biết đâu có ai đó nghe được",
  "khoan đã, đừng làm vậy",
  "Giờ tớ nên làm gì?",
  "Hay cậu thử gọi cho cảnh sát xem. Họ có thể lần ra vị trí",
  "Hét to lên biết đâu có người khác nghe",
  "Họ dừng xe lại",
  "Không kjhong",
  "djvznnnnnnnzc",
  "Lisa. Có chuyenj gì vậy?",
  "imghttps://images.pond5.com/white-glove-hand-holding-bloody-footage-054934724_iconl.jpeg",
  "Tao gieets no roi, check my mess",
  // 3
  // 4
  // 5
  // 6
  // 7
  //8
  // CHAT CÓ SẴN
  "fix bug chưa m?",
  "đang đi chơi với crush fix gì ba",
  "imghttps://i.imgur.com/Lwjx2GM.jpg",
  "ngon z ta",
  "hehe",
  "rãnh k chú",
  "giúp với",
  "imghttps://user-images.githubusercontent.com/1610503/30879342-0052f432-a2b4-11e7-8848-eb19f8f1db0b.png",
  "khongggggg",
  "jen oiwiii, mai sinh nhật bạn ấy r",
  "cho t lời khueyen mua quà với",
  "t được gì nếu giúp m??",
  "Sự tôn trọng",
  "Mua cu giả 2 đầu dẻo màu xanh chuối",
  "ok cảm ơn nhe",
  "queo cơm",
  "alo alo",
  "gì đó ku",
  "nãy thấy hình này hài quá gửi m xem",
  "imghttps://www.meme-arsenal.com/memes/8da21b55bbdc8815b9325894b45eab6d.jpg",
  "nhìn mặt nó hài gê",
  "haha",
  "2222",
  "gì nhóc",
  "ăn cơm chưa",
  "rồi, ông ăn chưa",
  "rồi luôn, hehe",
  "hello!",
  "?",
  "t có cái này muốn nói...",
  "đừng",
  "ok bờ rồ",
  "Tin nhắn đã xóa",
  "Lô cc",
  "hello",
  "[Tin nhắn tự động] Tôi đang ngủ, xin đừng làm phiền!",
  "Ê, dậy chưa",
  "Ngủ như heo z cô nương",
  "Gấp, Backend bị DDOS sập rồi",
  "Bạn ơi, lỗ nhị lủng rồi",
  "imghttps://taoanhonline.com/wp-content/uploads/2020/02/anh-tam-trang-14.jpg?v=1582376124",
  "cuuws",
  "sos",
  "t bị ai bắt cóc r",
  "giupz tao với toao sợ quá",
  "Giờ thiên tới ròi homie ơiii",
  "",
  // END CHAT CÓ SẴN // Từ đây vị trí trong mảng = line - 10
  "Tớ đã gọi rồi, họ bảo là...",
  "Sẽ tìm vị trí của tớ sớm",
  "Nhưng lúc nãy mất sóng",
  "Giờ tớ chỉ có thể nhắn với cậu",
  "Tớ sẽ ở đây, cố lên nhé",
  "Thôi, ngu thì chết, tui đi ngủ",
  "Đồ chó đẻ",
  "Xe đnag chậm lại",
  "Nó dừng hẳn rồi",
  "Làm sao đây...",
  "Giả vờ bất tỉnh đi",
  "Nó vừa mở cửa thì vùng chạy",
  "imghttps://t3.ftcdn.net/jpg/04/43/55/66/360_F_443556602_BlWny5kmuU7xlqqSxvUmprkzWQJZeQRD.jpg",
  "Xin là xin... qsr_y6PdbFE",
  "Ê thằng ngu, tao bắn nó rồi :))))",
  "ok...",
  "này, sao rồi..",
  "Tớ đang ở trong một ngôi rất lớn",
  "trong một căn phòng",
  "tụi nó ra ngoài để tớ lại",
  "Thử xem xung quanh có gì k",
  "xem cửa có khóa k?",
  "Tớ tìm thấy một con dao nhỏ",
  "Tốt lắm, hãy giữ nó",
  "Đừng lấy!",
  "Cửa khóa rồi",
  "T nghe thấy có ai đó đến",
  "Giả vờ ngất tiếp đi",
  "Hắn mở cửa thì cậu chạy nhanh ra",
  "Giả vờ ngất tiếp đi", // co dao
  "Hắn mở cửa thì cậu đâm hắn rồi chạy",
  "Hắn chụp 1 tấm ảnh rồi bỏ đi rồi",
  "Cậu thử nhảy qua cửa sổ được không?",
  "Nằm yêu chờ cảnh sát đi..",
  "Nằm yêu chờ cảnh sát đi..", // co dao
  "T đâm chết 1 tên rồi,",
  "t trốn trong 1 phòng khác", // co dao
  "trong này tối quá, khoan đã..",
  "gì thế...", // co dao
  "Tạ ơn chúa",
  "Tớ nghe thấy tiếng còi cảnh sát",
  "Có lẽ họ đã định vị đc cái đt",
  "Tớ cũng nghe thấy...", // k dao
  "Tót rồi, cậu sẽ thoát được mà!",
  "trong phòng này có người",
  "hắn đnag xem laptop",
  "hắn chưa nhận ra tớ đã vào đây",
  "mẹ nó, tớ sẽ giết hắn luôn",
  "Khoan dãdjhgfsaghwjjjjjjjjjjjjjjjj",
  "...",
  "chúa oiwiiiiiiiiii, đó là cậu",
  "là cậu, tại sao vậy",
  "khôngg",
  "Tớ cũng nghe thấy...", // co dao
  "ý cậu là sao??",
  "tớ cũng đang ở đó",
  "hãy nhìn ra cửa",
  "tớ cũng đang ở đó", // dao
  "hãy nhìn ra cửa", // dao
  "chúa ơi, có phải cậu đứng đó k?",
  "cậu làm gì ở đây thế",
  "cậu không sao chứ?",
  "tớ ổn, tớ đến cứu cậu đây",
  "tất cả chuyện này là trò đùa của tớ!",
  "có ai đó đang đến",
  "ơ, là cậu à?",
  "cảnh sát sắp đến rồi",
  "tớ phải hành động...",
  "Here's Johnnfjdhhhhhfdjfdbxv",
  "tớ yêu cậu...",
  "...ôm nhau nào",
  "...cùng ra khỏi đây thôi",
  "...",
  "vui không? haha haha ahah hahaa hah ha",
  "Tớ hận cậu",
  "cho cả cuộc đời này",
  "đừng để tớ thấy cậu một lần nào nữa",
  "cậu điên rồi",
  "Đừng giận, hãy nghe tớ giải thích dQw4w9WgXcQ",
  "Tao điên? VaYljknzCkQ",
  "được thôi, đến đây...",
  "nhưng, làm thế nào cậu đến được đây?",
  "tớ bay",
  "chà tớ đến bằng...",
  "Suy nghĩ đi. Làm sao cậu đến được đây? Ta đang ở đâu thế này?",
  "Là sao nhỉ? Mình đang mơ à????",
  "Cậu chỉ đang ngủ thôi. Đây là bài học đầu tiên của cậu.",
  "Ôi không, INCEPTIONNNNNNNNNNNNNNNNNNN",
  "1111",
  "1111",
  "2222",
  "44444",
];

export default convertChat;
